name: work_reminder_bot
description: Bot qui envoie un rappel de travail tous les jours Ã  17h
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  mineral: ^4.2.0
  mineral_cache: ^1.2.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
